name: Java Multi ModuleLayer Study

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package
      
    - name: Boot layer check
      run: mvn -q -f use exec:exec

    - name: Single layer check
      run: mvn -q -f use exec:exec -Dexec.appArgs=single
      
    - name: Double layer check
      run: mvn -q -f use exec:exec -Dexec.appArgs=double
      
    - name: Multi layer check
      run: mvn -q -f use exec:exec -Dexec.appArgs=multi
      
